[window]

opacity = 1.0

padding.x = 10
padding.y = 10

decorations = "none"
decorations_theme_variant = "Dark" # "Loght"

[font]
normal = { family = "JetBrainsMono", style = "Bold" }
bold = { family = "JetBrainsMono", style = "Bold" }
italic = { family = "JetBrainsMono", style = "Bold Italic" } # optional
bold_italic = { family = "JetBrainsMono", style = "Bold Italic" } # optional
size = 10.0  # Adjust as desired

[cursor]
style = { shape = "Beam" }
unfocused_hollow = false

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.normal]
black   = "#1c1c1c"
red     = "#af005f"
green   = "#5faf00"
yellow  = "#d7af5f"
blue    = "#5fafd7"
magenta = "#808080"
cyan    = "#d7875f"
white   = "#d0d0d0"

[colors.bright]
black   = "#585858"
red     = "#5faf5f"
green   = "#afd700"
yellow  = "#af87d7"
blue    = "#ffaf00"
magenta = "#ff5faf"
cyan    = "#00afaf"
white   = "#5f8787"