#!/bash/sh

# Most common 1000 pings made by devices.
# Requires [bind-tools] to work.

dig graph.facebook.com
dig ext2.temp-mail.org
dig i.instagram.com
dig edge-mqtt.facebook.com
dig gateway.icloud.com
dig play.googleapis.com
dig clients2.google.com
dig p168-fmfmobile.icloud.com
dig i.ytimg.com
dig accounts.google.com
dig www.youtube.com
dig connectivitycheck.gstatic.com
dig clients4.google.com
dig ipv6.msftconnecttest.com
dig web.facebook.com
dig youtubei.googleapis.com
dig signaler-pa.clients6.google.com
dig gateway.facebook.com
dig b-graph.facebook.com
dig time.apple.com
dig ssl.gstatic.com
dig www.facebook.com
dig mtalk.google.com
dig play-fe.googleapis.com
dig ocsp2.apple.com
dig chat-e2ee-mini.facebook.com
dig optimizationguide-pa.googleapis.com
dig android.clients.google.com
dig chatgpt.com
dig star.fallback.c10r.facebook.com
dig play-lh.googleusercontent.com
dig prod-lt-playstoregatewayadapter-pa.googleapis.com
dig apac-asia-courier-4.push-apple.com.akadns.net
dig clients3.google.com
dig bag.itunes.apple.com
dig sg.tdatamaster.com
dig yt3.ggpht.com
dig fmfmobile.fe2.apple-dns.net
dig playstoregatewayadapter-pa.googleapis.com
dig b-api.facebook.com
dig api.facebook.com
dig google.com
dig www.gstatic.com
dig mail.google.com
dig g.whatsapp.net
dig www.googleapis.com
dig 2.android.pool.ntp.org
dig v20.events.data.microsoft.com
dig play.google.com
dig lh3.googleusercontent.com
dig gateway.instagram.com
dig settings-win.data.microsoft.com
dig update.googleapis.com
dig mesu.apple.com
dig static.whatsapp.net
dig mqtt-mini.facebook.com
dig oauthaccountmanager.googleapis.com
dig chat-e2ee.facebook.com
dig android.googleapis.com
dig z-p42-chat-e2ee-ig.facebook.com
dig catalog.gamepass.com
dig v10.events.data.microsoft.com
dig ogs.google.com
dig clientservices.googleapis.com
dig userpresence.xboxlive.com
dig notifications-pa.googleapis.com
dig m.facebook.com
dig roaming.officeapps.live.com
dig ocsp2.g.aaplimg.com
dig content-autofill.googleapis.com
dig analytics.hamrostack.com
dig ping.archlinux.org
dig userlocation.googleapis.com
dig footprints-pa.googleapis.com
dig mask-canary.icloud.com
dig graph.instagram.com
dig x.blueduckredapple.com
dig api.bidmachine.io
dig x.thecatmachine.com
dig x.everestop.io
dig s.youtube.com
dig mask-h2.icloud.com
dig www.google.com
dig app-measurement.com
dig netcts.cdn-apple.com
dig beacons.gcp.gvt2.com
dig api.smoot.apple.com
dig beacons.gvt2.com
dig beacons4.gvt2.com
dig beacons2.gvt2.com
dig beacons3.gvt2.com
dig metrics.icloud.com
dig beacons5.gvt3.com
dig beacons5.gvt2.com
dig googleads.g.doubleclick.net
dig batchlogging4-noneu.truecaller.com
dig mask.icloud.com
dig firebase-settings.crashlytics.com
dig httpdns-push.heytapmobile.com
dig xp.apple.com
dig ca.iadsdk.apple.com
dig vulcan5.branch.io
dig ogads-pa.clients6.google.com
dig graph-fallback.instagram.com
dig app-analytics-services.com
dig mask-api.icloud.com
dig region1.app-analytics-services.com
dig g.live.com
dig suggestqueries.google.com
dig crashlyticsreports-pa.googleapis.com
dig arc.msn.com
dig frontier.tiktokv.com
dig api.revenuads.com
dig ire-dsu.shalltry.com
dig upu.samsungelectronics.com
dig app.adjust.net.in
dig xpu.samsungelectronics.com
dig app.adjust.com
dig app.adjust.world
dig nexusrules.officeapps.live.com
dig api.antibanads.com
dig cstat.cdn-apple.com
dig ios.crashsight.wetest.net
dig www.googletagmanager.com
dig bstream.kzhi.tech
dig ios.dns.nextdns.io
dig ipv4only.arpa
dig profile.accounts.firefox.com
dig firefox-settings-attachments.cdn.mozilla.net
dig detectportal.firefox.com
dig time.google.com
dig media.fbir7-1.fna.whatsapp.net
dig a1818.dscw154.akamai.net
dig privacy-gateway.cloudflare.com
dig 12-courier.push.apple.com
dig firefox.settings.services.mozilla.com
dig push.services.mozilla.com
dig accounts.youtube.com
dig torrent.bishab.com.np
dig home.bishab.com.np
dig ad.bishab.com.np
dig tv.bishab.com.np
dig sponsor.ajay.app
dig time.cloudflare.com
dig youtube-ui.l.google.com
dig p113-caldav.icloud.com
dig bsync31-normal-useast2a.tiktokv.com
dig gecko16-normal-useast2a.tiktokv.com
dig a1851.b.akamai.net
dig sf16-ies-music-va.tiktokcdn.com
dig direct.quic-core-proxy-gcpsg-v3.gcpsg.byteglb.com
dig api22-core.tiktokv.com
dig api16-core.tiktokv.com
dig pull-flv-l10-gcp01.tiktokcdn.com
dig pull-hls-f77-gcp01.tiktokcdn.com
dig 1787221766.rsc.cdn77.org
dig cl-gl036e4fc3.gcdn.co
dig 1053058463.rsc.cdn77.org
dig pull-flv-f58-tt03.fcdn.eu.tiktokcdn.com
dig push-fcdn-base1.s.bytefcdn-oversea.com
dig push-rtmp-f5-vr-gcp01.tiktokcdn.com
dig pull-flv-o77-sg01.eu.tiktokcdn.com
dig pull-cmaf-f77-gcp01.tiktokcdn.com
dig a1491.z.akamai.net
dig pull-cmaf-f16-tt02-tt03.fcdn.eu.tiktokcdn.com
dig 1911873314.rsc.cdn77.org
dig pull-base3.s.bytefcdn-ttpeu.com
dig 1845588971.rsc.cdn77.org
dig valid-apple.g.aaplimg.com
dig valid.apple.com
dig gdmf.v.aaplimg.com
dig p168-contacts.icloud.com
dig cf-st.sc-cdn.net
dig e10499.dsce9.akamaiedge.net
dig configuration.ls.apple.com
dig ohttp-relay1.fastly-edge.com
dig e4686.dsce9.akamaiedge.net
dig gspe35-ssl.ls.apple.com
dig get-bx.g.aaplimg.com
dig a1931.dscgi3.akamai.net
dig cloudflare-dns.com
dig image.tmdb.org
dig metadata-static.plex.tv
dig images.plex.tv
dig scrobbles.plex.tv
dig vdterms.samsungcloudsolution.com
dig app-analytics-v2.snapchat.com
dig wikipedia.org
dig wikimedia.org
dig facebook.com
dig apple.com
dig fp2e7a.wpc.phicdn.net
dig ocsp.digicert.com
dig mouseflow.com
dig sentry-cdn.com
dig pixel.facebook.com
dig advertising.twitter.com
dig ads.reddit.com
dig analytics-sg.tiktok.com
dig yandexadexchange.net
dig graph.facebook.com
dig ext2.temp-mail.org
dig i.instagram.com
dig edge-mqtt.facebook.com
dig gateway.icloud.com
dig play.googleapis.com
dig clients2.google.com
dig p168-fmfmobile.icloud.com
dig i.ytimg.com
dig accounts.google.com
dig www.youtube.com
dig connectivitycheck.gstatic.com
dig clients4.google.com
dig ipv6.msftconnecttest.com
dig web.facebook.com
dig youtubei.googleapis.com
dig signaler-pa.clients6.google.com
dig gateway.facebook.com
dig b-graph.facebook.com
dig time.apple.com
dig ssl.gstatic.com
dig www.facebook.com
dig mtalk.google.com
dig play-fe.googleapis.com
dig ocsp2.apple.com
dig chat-e2ee-mini.facebook.com
dig optimizationguide-pa.googleapis.com
dig android.clients.google.com
dig chatgpt.com
dig star.fallback.c10r.facebook.com
dig play-lh.googleusercontent.com
dig prod-lt-playstoregatewayadapter-pa.googleapis.com
dig apac-asia-courier-4.push-apple.com.akadns.net
dig clients3.google.com
dig bag.itunes.apple.com
dig sg.tdatamaster.com
dig yt3.ggpht.com
dig fmfmobile.fe2.apple-dns.net
dig playstoregatewayadapter-pa.googleapis.com
dig b-api.facebook.com
dig api.facebook.com
dig google.com
dig www.gstatic.com
dig mail.google.com
dig g.whatsapp.net
dig www.googleapis.com
dig 2.android.pool.ntp.org
dig v20.events.data.microsoft.com
dig play.google.com
dig lh3.googleusercontent.com
dig gateway.instagram.com
dig settings-win.data.microsoft.com
dig update.googleapis.com
dig mesu.apple.com
dig static.whatsapp.net
dig mqtt-mini.facebook.com
dig oauthaccountmanager.googleapis.com
dig chat-e2ee.facebook.com
dig android.googleapis.com
dig z-p42-chat-e2ee-ig.facebook.com
dig catalog.gamepass.com
dig v10.events.data.microsoft.com
dig ogs.google.com
dig clientservices.googleapis.com
dig userpresence.xboxlive.com
dig notifications-pa.googleapis.com
dig m.facebook.com
dig roaming.officeapps.live.com
dig ocsp2.g.aaplimg.com
dig content-autofill.googleapis.com
dig analytics.hamrostack.com
dig ping.archlinux.org
dig userlocation.googleapis.com
dig footprints-pa.googleapis.com
dig mask-canary.icloud.com
dig graph.instagram.com
dig x.blueduckredapple.com
dig api.bidmachine.io
dig x.thecatmachine.com
dig x.everestop.io
dig s.youtube.com
dig mask-h2.icloud.com
dig www.google.com
dig app-measurement.com
dig netcts.cdn-apple.com
dig beacons.gcp.gvt2.com
dig api.smoot.apple.com
dig beacons.gvt2.com
dig beacons4.gvt2.com
dig beacons2.gvt2.com
dig beacons3.gvt2.com
dig metrics.icloud.com
dig beacons5.gvt3.com
dig beacons5.gvt2.com
dig googleads.g.doubleclick.net
dig batchlogging4-noneu.truecaller.com
dig mask.icloud.com
dig firebase-settings.crashlytics.com
dig httpdns-push.heytapmobile.com
dig xp.apple.com
dig ca.iadsdk.apple.com
dig vulcan5.branch.io
dig ogads-pa.clients6.google.com
dig graph-fallback.instagram.com
dig app-analytics-services.com
dig mask-api.icloud.com
dig region1.app-analytics-services.com
dig g.live.com
dig suggestqueries.google.com
dig crashlyticsreports-pa.googleapis.com
dig arc.msn.com
dig frontier.tiktokv.com
dig api.revenuads.com
dig ire-dsu.shalltry.com
dig upu.samsungelectronics.com
dig app.adjust.net.in
dig xpu.samsungelectronics.com
dig app.adjust.com
dig app.adjust.world
dig nexusrules.officeapps.live.com
dig api.antibanads.com
dig cstat.cdn-apple.com
dig ios.crashsight.wetest.net
dig www.googletagmanager.com
dig bstream.kzhi.tech
dig ios.dns.nextdns.io
dig ipv4only.arpa
dig profile.accounts.firefox.com
dig firefox-settings-attachments.cdn.mozilla.net
dig detectportal.firefox.com
dig time.google.com
dig media.fbir7-1.fna.whatsapp.net
dig a1818.dscw154.akamai.net
dig privacy-gateway.cloudflare.com
dig 12-courier.push.apple.com
dig firefox.settings.services.mozilla.com
dig push.services.mozilla.com
dig accounts.youtube.com
dig torrent.bishab.com.np
dig home.bishab.com.np
dig ad.bishab.com.np
dig tv.bishab.com.np
dig sponsor.ajay.app
dig time.cloudflare.com
dig youtube-ui.l.google.com
dig p113-caldav.icloud.com
dig bsync31-normal-useast2a.tiktokv.com
dig gecko16-normal-useast2a.tiktokv.com
dig a1851.b.akamai.net
dig sf16-ies-music-va.tiktokcdn.com
dig direct.quic-core-proxy-gcpsg-v3.gcpsg.byteglb.com
dig api22-core.tiktokv.com
dig api16-core.tiktokv.com
dig pull-flv-l10-gcp01.tiktokcdn.com
dig pull-hls-f77-gcp01.tiktokcdn.com
dig 1787221766.rsc.cdn77.org
dig cl-gl036e4fc3.gcdn.co
dig 1053058463.rsc.cdn77.org
dig pull-flv-f58-tt03.fcdn.eu.tiktokcdn.com
dig push-fcdn-base1.s.bytefcdn-oversea.com
dig push-rtmp-f5-vr-gcp01.tiktokcdn.com
dig pull-flv-o77-sg01.eu.tiktokcdn.com
dig pull-cmaf-f77-gcp01.tiktokcdn.com
dig a1491.z.akamai.net
dig pull-cmaf-f16-tt02-tt03.fcdn.eu.tiktokcdn.com
dig 1911873314.rsc.cdn77.org
dig pull-base3.s.bytefcdn-ttpeu.com
dig 1845588971.rsc.cdn77.org
dig valid-apple.g.aaplimg.com
dig valid.apple.com
dig gdmf.v.aaplimg.com
dig p168-contacts.icloud.com
dig cf-st.sc-cdn.net
dig e10499.dsce9.akamaiedge.net
dig configuration.ls.apple.com
dig ohttp-relay1.fastly-edge.com
dig e4686.dsce9.akamaiedge.net
dig gspe35-ssl.ls.apple.com
dig get-bx.g.aaplimg.com
dig a1931.dscgi3.akamai.net
dig cloudflare-dns.com
dig image.tmdb.org
dig metadata-static.plex.tv
dig images.plex.tv
dig scrobbles.plex.tv
dig vdterms.samsungcloudsolution.com
dig app-analytics-v2.snapchat.com
dig wikipedia.org
dig wikimedia.org
dig facebook.com
dig apple.com
dig fp2e7a.wpc.phicdn.net
dig ocsp.digicert.com
dig mouseflow.com
dig sentry-cdn.com
dig pixel.facebook.com
dig advertising.twitter.com
dig ads.reddit.com
dig analytics-sg.tiktok.com
dig yandexadexchange.net
dig graph.facebook.com
dig ext2.temp-mail.org
dig i.instagram.com
dig edge-mqtt.facebook.com
dig gateway.icloud.com
dig play.googleapis.com
dig clients2.google.com
dig p168-fmfmobile.icloud.com
dig i.ytimg.com
dig accounts.google.com
dig www.youtube.com
dig connectivitycheck.gstatic.com
dig clients4.google.com
dig ipv6.msftconnecttest.com
dig web.facebook.com
dig youtubei.googleapis.com
dig signaler-pa.clients6.google.com
dig gateway.facebook.com
dig b-graph.facebook.com
dig time.apple.com
dig ssl.gstatic.com
dig www.facebook.com
dig mtalk.google.com
dig play-fe.googleapis.com
dig ocsp2.apple.com
dig chat-e2ee-mini.facebook.com
dig optimizationguide-pa.googleapis.com
dig android.clients.google.com
dig chatgpt.com
dig star.fallback.c10r.facebook.com
dig play-lh.googleusercontent.com
dig prod-lt-playstoregatewayadapter-pa.googleapis.com
dig apac-asia-courier-4.push-apple.com.akadns.net
dig clients3.google.com
dig bag.itunes.apple.com
dig sg.tdatamaster.com
dig yt3.ggpht.com
dig fmfmobile.fe2.apple-dns.net
dig playstoregatewayadapter-pa.googleapis.com
dig b-api.facebook.com
dig api.facebook.com
dig google.com
dig www.gstatic.com
dig mail.google.com
dig g.whatsapp.net
dig www.googleapis.com
dig 2.android.pool.ntp.org
dig v20.events.data.microsoft.com
dig play.google.com
dig lh3.googleusercontent.com
dig gateway.instagram.com
dig settings-win.data.microsoft.com
dig update.googleapis.com
dig mesu.apple.com
dig static.whatsapp.net
dig mqtt-mini.facebook.com
dig oauthaccountmanager.googleapis.com
dig chat-e2ee.facebook.com
dig android.googleapis.com
dig z-p42-chat-e2ee-ig.facebook.com
dig catalog.gamepass.com
dig v10.events.data.microsoft.com
dig ogs.google.com
dig clientservices.googleapis.com
dig userpresence.xboxlive.com
dig notifications-pa.googleapis.com
dig m.facebook.com
dig roaming.officeapps.live.com
dig ocsp2.g.aaplimg.com
dig content-autofill.googleapis.com
dig analytics.hamrostack.com
dig ping.archlinux.org
dig userlocation.googleapis.com
dig footprints-pa.googleapis.com
dig mask-canary.icloud.com
dig graph.instagram.com
dig x.blueduckredapple.com
dig api.bidmachine.io
dig x.thecatmachine.com
dig x.everestop.io
dig s.youtube.com
dig mask-h2.icloud.com
dig www.google.com
dig app-measurement.com
dig netcts.cdn-apple.com
dig beacons.gcp.gvt2.com
dig api.smoot.apple.com
dig beacons.gvt2.com
dig beacons4.gvt2.com
dig beacons2.gvt2.com
dig beacons3.gvt2.com
dig metrics.icloud.com
dig beacons5.gvt3.com
dig beacons5.gvt2.com
dig googleads.g.doubleclick.net
dig batchlogging4-noneu.truecaller.com
dig mask.icloud.com
dig firebase-settings.crashlytics.com
dig httpdns-push.heytapmobile.com
dig xp.apple.com
dig ca.iadsdk.apple.com
dig vulcan5.branch.io
dig ogads-pa.clients6.google.com
dig graph-fallback.instagram.com
dig app-analytics-services.com
dig mask-api.icloud.com
dig region1.app-analytics-services.com
dig g.live.com
dig suggestqueries.google.com
dig crashlyticsreports-pa.googleapis.com
dig arc.msn.com
dig frontier.tiktokv.com
dig api.revenuads.com
dig ire-dsu.shalltry.com
dig upu.samsungelectronics.com
dig app.adjust.net.in
dig xpu.samsungelectronics.com
dig app.adjust.com
dig app.adjust.world
dig nexusrules.officeapps.live.com
dig api.antibanads.com
dig cstat.cdn-apple.com
dig ios.crashsight.wetest.net
dig www.googletagmanager.com
dig bstream.kzhi.tech
dig ios.dns.nextdns.io
dig ipv4only.arpa
dig profile.accounts.firefox.com
dig firefox-settings-attachments.cdn.mozilla.net
dig detectportal.firefox.com
dig time.google.com
dig media.fbir7-1.fna.whatsapp.net
dig a1818.dscw154.akamai.net
dig privacy-gateway.cloudflare.com
dig 12-courier.push.apple.com
dig firefox.settings.services.mozilla.com
dig push.services.mozilla.com
dig accounts.youtube.com
dig torrent.bishab.com.np
dig home.bishab.com.np
dig ad.bishab.com.np
dig tv.bishab.com.np
dig sponsor.ajay.app
dig time.cloudflare.com
dig youtube-ui.l.google.com
dig p113-caldav.icloud.com
dig bsync31-normal-useast2a.tiktokv.com
dig gecko16-normal-useast2a.tiktokv.com
dig a1851.b.akamai.net
dig sf16-ies-music-va.tiktokcdn.com
dig direct.quic-core-proxy-gcpsg-v3.gcpsg.byteglb.com
dig api22-core.tiktokv.com
dig api16-core.tiktokv.com
dig pull-flv-l10-gcp01.tiktokcdn.com
dig pull-hls-f77-gcp01.tiktokcdn.com
dig 1787221766.rsc.cdn77.org
dig cl-gl036e4fc3.gcdn.co
dig 1053058463.rsc.cdn77.org
dig pull-flv-f58-tt03.fcdn.eu.tiktokcdn.com
dig push-fcdn-base1.s.bytefcdn-oversea.com
dig push-rtmp-f5-vr-gcp01.tiktokcdn.com
dig pull-flv-o77-sg01.eu.tiktokcdn.com
dig pull-cmaf-f77-gcp01.tiktokcdn.com
dig a1491.z.akamai.net
dig pull-cmaf-f16-tt02-tt03.fcdn.eu.tiktokcdn.com
dig 1911873314.rsc.cdn77.org
dig pull-base3.s.bytefcdn-ttpeu.com
dig 1845588971.rsc.cdn77.org
dig valid-apple.g.aaplimg.com
dig valid.apple.com
dig gdmf.v.aaplimg.com
dig p168-contacts.icloud.com
dig cf-st.sc-cdn.net
dig e10499.dsce9.akamaiedge.net
dig configuration.ls.apple.com
dig ohttp-relay1.fastly-edge.com
dig e4686.dsce9.akamaiedge.net
dig gspe35-ssl.ls.apple.com
dig get-bx.g.aaplimg.com
dig a1931.dscgi3.akamai.net
dig cloudflare-dns.com
dig image.tmdb.org
dig metadata-static.plex.tv
dig images.plex.tv
dig scrobbles.plex.tv
dig vdterms.samsungcloudsolution.com
dig app-analytics-v2.snapchat.com
dig wikipedia.org
dig wikimedia.org
dig facebook.com
dig apple.com
dig fp2e7a.wpc.phicdn.net
dig ocsp.digicert.com
dig mouseflow.com
dig sentry-cdn.com
dig pixel.facebook.com
dig advertising.twitter.com
dig ads.reddit.com
dig analytics-sg.tiktok.com
dig yandexadexchange.net
dig graph.facebook.com
dig ext2.temp-mail.org
dig i.instagram.com
dig edge-mqtt.facebook.com
dig gateway.icloud.com
dig play.googleapis.com
dig clients2.google.com
dig p168-fmfmobile.icloud.com
dig i.ytimg.com
dig accounts.google.com
dig www.youtube.com
dig connectivitycheck.gstatic.com
dig clients4.google.com
dig ipv6.msftconnecttest.com
dig web.facebook.com
dig youtubei.googleapis.com
dig signaler-pa.clients6.google.com
dig gateway.facebook.com
dig b-graph.facebook.com
dig time.apple.com
dig ssl.gstatic.com
dig www.facebook.com
dig mtalk.google.com
dig play-fe.googleapis.com
dig ocsp2.apple.com
dig chat-e2ee-mini.facebook.com
dig optimizationguide-pa.googleapis.com
dig android.clients.google.com
dig chatgpt.com
dig star.fallback.c10r.facebook.com
dig play-lh.googleusercontent.com
dig prod-lt-playstoregatewayadapter-pa.googleapis.com
dig apac-asia-courier-4.push-apple.com.akadns.net
dig clients3.google.com
dig bag.itunes.apple.com
dig sg.tdatamaster.com
dig yt3.ggpht.com
dig fmfmobile.fe2.apple-dns.net
dig playstoregatewayadapter-pa.googleapis.com
dig b-api.facebook.com
dig api.facebook.com
dig google.com
dig www.gstatic.com
dig mail.google.com
dig g.whatsapp.net
dig www.googleapis.com
dig 2.android.pool.ntp.org
dig v20.events.data.microsoft.com
dig play.google.com
dig lh3.googleusercontent.com
dig gateway.instagram.com
dig settings-win.data.microsoft.com
dig update.googleapis.com
dig mesu.apple.com
dig static.whatsapp.net
dig mqtt-mini.facebook.com
dig oauthaccountmanager.googleapis.com
dig chat-e2ee.facebook.com
dig android.googleapis.com
dig z-p42-chat-e2ee-ig.facebook.com
dig catalog.gamepass.com
dig v10.events.data.microsoft.com
dig ogs.google.com
dig clientservices.googleapis.com
dig userpresence.xboxlive.com
dig notifications-pa.googleapis.com
dig m.facebook.com
dig roaming.officeapps.live.com
dig ocsp2.g.aaplimg.com
dig content-autofill.googleapis.com
dig analytics.hamrostack.com
dig ping.archlinux.org
dig userlocation.googleapis.com
dig footprints-pa.googleapis.com
dig mask-canary.icloud.com
dig graph.instagram.com
dig x.blueduckredapple.com
dig api.bidmachine.io
dig x.thecatmachine.com
dig x.everestop.io
dig s.youtube.com
dig mask-h2.icloud.com
dig www.google.com
dig app-measurement.com
dig netcts.cdn-apple.com
dig beacons.gcp.gvt2.com
dig api.smoot.apple.com
dig beacons.gvt2.com
dig beacons4.gvt2.com
dig beacons2.gvt2.com
dig beacons3.gvt2.com
dig metrics.icloud.com
dig beacons5.gvt3.com
dig beacons5.gvt2.com
dig googleads.g.doubleclick.net
dig batchlogging4-noneu.truecaller.com
dig mask.icloud.com
dig firebase-settings.crashlytics.com
dig httpdns-push.heytapmobile.com
dig xp.apple.com
dig ca.iadsdk.apple.com
dig vulcan5.branch.io
dig ogads-pa.clients6.google.com
dig graph-fallback.instagram.com
dig app-analytics-services.com
dig mask-api.icloud.com
dig region1.app-analytics-services.com
dig g.live.com
dig suggestqueries.google.com
dig crashlyticsreports-pa.googleapis.com
dig arc.msn.com
dig frontier.tiktokv.com
dig api.revenuads.com
dig ire-dsu.shalltry.com
dig upu.samsungelectronics.com
dig app.adjust.net.in
dig xpu.samsungelectronics.com
dig app.adjust.com
dig app.adjust.world
dig nexusrules.officeapps.live.com
dig api.antibanads.com
dig cstat.cdn-apple.com
dig ios.crashsight.wetest.net
dig www.googletagmanager.com
dig bstream.kzhi.tech
dig ios.dns.nextdns.io
dig ipv4only.arpa
dig profile.accounts.firefox.com
dig firefox-settings-attachments.cdn.mozilla.net
dig detectportal.firefox.com
dig time.google.com
dig media.fbir7-1.fna.whatsapp.net
dig a1818.dscw154.akamai.net
dig privacy-gateway.cloudflare.com
dig 12-courier.push.apple.com
dig firefox.settings.services.mozilla.com
dig push.services.mozilla.com
dig accounts.youtube.com
dig torrent.bishab.com.np
dig home.bishab.com.np
dig ad.bishab.com.np
dig tv.bishab.com.np
dig sponsor.ajay.app
dig time.cloudflare.com
dig youtube-ui.l.google.com
dig p113-caldav.icloud.com
dig bsync31-normal-useast2a.tiktokv.com
dig gecko16-normal-useast2a.tiktokv.com
dig a1851.b.akamai.net
dig sf16-ies-music-va.tiktokcdn.com
dig direct.quic-core-proxy-gcpsg-v3.gcpsg.byteglb.com
dig api22-core.tiktokv.com
dig api16-core.tiktokv.com
dig pull-flv-l10-gcp01.tiktokcdn.com
dig pull-hls-f77-gcp01.tiktokcdn.com
dig 1787221766.rsc.cdn77.org
dig cl-gl036e4fc3.gcdn.co
dig 1053058463.rsc.cdn77.org
dig pull-flv-f58-tt03.fcdn.eu.tiktokcdn.com
dig push-fcdn-base1.s.bytefcdn-oversea.com
dig push-rtmp-f5-vr-gcp01.tiktokcdn.com
dig pull-flv-o77-sg01.eu.tiktokcdn.com
dig pull-cmaf-f77-gcp01.tiktokcdn.com
dig a1491.z.akamai.net
dig pull-cmaf-f16-tt02-tt03.fcdn.eu.tiktokcdn.com
dig 1911873314.rsc.cdn77.org
dig pull-base3.s.bytefcdn-ttpeu.com
dig 1845588971.rsc.cdn77.org
dig valid-apple.g.aaplimg.com
dig valid.apple.com
dig gdmf.v.aaplimg.com
dig p168-contacts.icloud.com
dig cf-st.sc-cdn.net
dig e10499.dsce9.akamaiedge.net
dig configuration.ls.apple.com
dig ohttp-relay1.fastly-edge.com
dig e4686.dsce9.akamaiedge.net
dig gspe35-ssl.ls.apple.com
dig get-bx.g.aaplimg.com
dig a1931.dscgi3.akamai.net
dig cloudflare-dns.com
dig image.tmdb.org
dig metadata-static.plex.tv
dig images.plex.tv
dig scrobbles.plex.tv
dig vdterms.samsungcloudsolution.com
dig app-analytics-v2.snapchat.com
dig wikipedia.org
dig wikimedia.org
dig facebook.com
dig apple.com
dig fp2e7a.wpc.phicdn.net
dig ocsp.digicert.com
dig mouseflow.com
dig sentry-cdn.com
dig pixel.facebook.com
dig advertising.twitter.com
dig ads.reddit.com
dig analytics-sg.tiktok.com
dig yandexadexchange.net
dig graph.facebook.com
dig ext2.temp-mail.org
dig i.instagram.com
dig edge-mqtt.facebook.com
dig gateway.icloud.com
dig play.googleapis.com
dig clients2.google.com
dig p168-fmfmobile.icloud.com
dig i.ytimg.com
dig accounts.google.com
dig www.youtube.com
dig connectivitycheck.gstatic.com
dig clients4.google.com
dig ipv6.msftconnecttest.com
dig web.facebook.com
dig youtubei.googleapis.com
dig signaler-pa.clients6.google.com
dig gateway.facebook.com
dig b-graph.facebook.com
dig time.apple.com
dig ssl.gstatic.com
dig www.facebook.com
dig mtalk.google.com
dig play-fe.googleapis.com
dig ocsp2.apple.com
dig chat-e2ee-mini.facebook.com
dig optimizationguide-pa.googleapis.com
dig android.clients.google.com
dig chatgpt.com
dig star.fallback.c10r.facebook.com
dig play-lh.googleusercontent.com
dig prod-lt-playstoregatewayadapter-pa.googleapis.com
dig apac-asia-courier-4.push-apple.com.akadns.net
dig clients3.google.com
dig bag.itunes.apple.com
dig sg.tdatamaster.com
dig yt3.ggpht.com
dig fmfmobile.fe2.apple-dns.net
dig playstoregatewayadapter-pa.googleapis.com
dig b-api.facebook.com
dig api.facebook.com
dig google.com
dig www.gstatic.com
dig mail.google.com
dig g.whatsapp.net
dig www.googleapis.com
dig 2.android.pool.ntp.org
dig v20.events.data.microsoft.com
dig play.google.com
dig lh3.googleusercontent.com
dig gateway.instagram.com
dig settings-win.data.microsoft.com
dig update.googleapis.com
dig mesu.apple.com
dig static.whatsapp.net
dig mqtt-mini.facebook.com
dig oauthaccountmanager.googleapis.com
dig chat-e2ee.facebook.com
dig android.googleapis.com
dig z-p42-chat-e2ee-ig.facebook.com
dig catalog.gamepass.com
dig v10.events.data.microsoft.com
dig ogs.google.com
dig clientservices.googleapis.com
dig userpresence.xboxlive.com
dig notifications-pa.googleapis.com
dig m.facebook.com
dig roaming.officeapps.live.com
dig ocsp2.g.aaplimg.com
dig content-autofill.googleapis.com
dig analytics.hamrostack.com
dig ping.archlinux.org
dig userlocation.googleapis.com
dig footprints-pa.googleapis.com
dig mask-canary.icloud.com
dig graph.instagram.com
dig x.blueduckredapple.com
dig api.bidmachine.io
dig x.thecatmachine.com
dig x.everestop.io
dig s.youtube.com
dig mask-h2.icloud.com
dig www.google.com
dig app-measurement.com
dig netcts.cdn-apple.com
dig beacons.gcp.gvt2.com
dig api.smoot.apple.com
dig beacons.gvt2.com
dig beacons4.gvt2.com
dig beacons2.gvt2.com
dig beacons3.gvt2.com
dig metrics.icloud.com
dig beacons5.gvt3.com
dig beacons5.gvt2.com
dig googleads.g.doubleclick.net
dig batchlogging4-noneu.truecaller.com
dig mask.icloud.com
dig firebase-settings.crashlytics.com
dig httpdns-push.heytapmobile.com
dig xp.apple.com
dig ca.iadsdk.apple.com
dig vulcan5.branch.io
dig ogads-pa.clients6.google.com
dig graph-fallback.instagram.com
dig app-analytics-services.com
dig mask-api.icloud.com
dig region1.app-analytics-services.com
dig g.live.com
dig suggestqueries.google.com
dig crashlyticsreports-pa.googleapis.com
dig arc.msn.com
dig frontier.tiktokv.com
dig api.revenuads.com
dig ire-dsu.shalltry.com
dig upu.samsungelectronics.com
dig app.adjust.net.in
dig xpu.samsungelectronics.com
dig app.adjust.com
dig app.adjust.world
dig nexusrules.officeapps.live.com
dig api.antibanads.com
dig cstat.cdn-apple.com
dig ios.crashsight.wetest.net
dig www.googletagmanager.com
dig bstream.kzhi.tech
dig ios.dns.nextdns.io
dig ipv4only.arpa
dig profile.accounts.firefox.com
dig firefox-settings-attachments.cdn.mozilla.net
dig detectportal.firefox.com
dig time.google.com
dig media.fbir7-1.fna.whatsapp.net
dig a1818.dscw154.akamai.net
dig privacy-gateway.cloudflare.com
dig 12-courier.push.apple.com
dig firefox.settings.services.mozilla.com
dig push.services.mozilla.com
dig accounts.youtube.com
dig torrent.bishab.com.np
dig home.bishab.com.np
dig ad.bishab.com.np
dig tv.bishab.com.np
dig sponsor.ajay.app
dig time.cloudflare.com
dig youtube-ui.l.google.com
dig p113-caldav.icloud.com
dig bsync31-normal-useast2a.tiktokv.com
dig gecko16-normal-useast2a.tiktokv.com
dig a1851.b.akamai.net
dig sf16-ies-music-va.tiktokcdn.com
dig direct.quic-core-proxy-gcpsg-v3.gcpsg.byteglb.com
dig api22-core.tiktokv.com
dig api16-core.tiktokv.com
dig pull-flv-l10-gcp01.tiktokcdn.com
dig pull-hls-f77-gcp01.tiktokcdn.com
dig 1787221766.rsc.cdn77.org
dig cl-gl036e4fc3.gcdn.co
dig 1053058463.rsc.cdn77.org
dig pull-flv-f58-tt03.fcdn.eu.tiktokcdn.com
dig push-fcdn-base1.s.bytefcdn-oversea.com
dig push-rtmp-f5-vr-gcp01.tiktokcdn.com
dig pull-flv-o77-sg01.eu.tiktokcdn.com
dig pull-cmaf-f77-gcp01.tiktokcdn.com
dig a1491.z.akamai.net
dig pull-cmaf-f16-tt02-tt03.fcdn.eu.tiktokcdn.com
dig 1911873314.rsc.cdn77.org
dig pull-base3.s.bytefcdn-ttpeu.com
dig 1845588971.rsc.cdn77.org
dig valid-apple.g.aaplimg.com
dig valid.apple.com
dig gdmf.v.aaplimg.com
dig p168-contacts.icloud.com
dig cf-st.sc-cdn.net
dig e10499.dsce9.akamaiedge.net
dig configuration.ls.apple.com
dig ohttp-relay1.fastly-edge.com
dig e4686.dsce9.akamaiedge.net
dig gspe35-ssl.ls.apple.com
dig get-bx.g.aaplimg.com
dig a1931.dscgi3.akamai.net
dig cloudflare-dns.com
dig image.tmdb.org
dig metadata-static.plex.tv
dig images.plex.tv
dig scrobbles.plex.tv
dig vdterms.samsungcloudsolution.com
dig app-analytics-v2.snapchat.com
dig wikipedia.org
dig wikimedia.org
dig facebook.com
dig apple.com
dig fp2e7a.wpc.phicdn.net
dig ocsp.digicert.com
dig mouseflow.com
dig sentry-cdn.com
dig pixel.facebook.com
dig advertising.twitter.com
dig ads.reddit.com
dig analytics-sg.tiktok.com
dig yandexadexchange.net